sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x --yes
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake cmake-data sqlite3 libboost-all-dev qt5-default
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make && ./tests/test