sudo: required
dist: xenial
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake
      - cmake-data
      - sqlite3
before_install:
  - sudo add-apt-repository -y universe
  - sudo apt-get -q update
  - sudo apt-get -y install libboost-all-dev
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7"; fi
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -Dbuild_gui=Off ..
script:
  - make
  - ./tests/tests
notifications:
  email: false

