sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - sourceline: 'ppa:kzemek/boost'
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - sqlite3
      - boost1.58
      - libboost-date-time1.58
      - libboost-thread1.58
      - libboost-system1.58
      - qt5-default
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7"; fi
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
script:
  - make && ./tests/test