sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
before_install:
  # Update apt lists (in order to install boost 1.58+)
  - cat /etc/apt/sources.list
  - cp /etc/apt/sources.list /tmp/sources.list
  - echo 'deb http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - echo 'deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse' >> /tmp/sources.list
  - sudo mv /tmp/sources.list /etc/apt/sources.list
addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - sqlite3
      - libboost-all-dev
      - qt5-default
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..
script:
  - make && ./tests/test