sudo: required
dist: xenial
language: cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang
      - cmake
      - cmake-data
      - sqlite3
before_install:
  - sudo add-apt-repository -y universe
  - sudo apt-get -q update
  - sudo apt-get -y install libboost-{chrono,program-options,date-time,thread,system,filesystem,regex,serialization}{-dev,.0}
install:
  - if [ "$CXX" = "g++" ]; then export CXX="clang++" CC="clang"; fi
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -Dbuild_gui=Off ..
script:
  - make
  - ./tests/tests
notifications:
  email: false

