sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: 'ppa:kzemek/boost'
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - sqlite3
      - boost1.58
      - libboost-date-time1.58
      - libboost-thread1.58
      - libboost-system1.58
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt571-trusty --yes
  - sudo apt-get update -qq
install:
  - sudo apt-get install qt57base qt57tools --force-yes
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_PREFIX_PATH=/opt/qt56 ..
script:
  - make && ./tests/test
notifications:
  email: false